services:
  - type: web
    plan: free
    name: Rename-Bot-4GB
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/SRim909263/Rename-Bot-4GB/tree/metadata.git      
    branch: metadata
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: STRING_SESSION
        sync: false
    autoDeploy: false
